In [75]:
# 1 Gradient Descent
# 2 cost function
# 3 Save Model Using Joblib And Pickle:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
df = pd.read_csv('test_scores.csv')
df.dtypes

name    object
math     int64
cs       int64
dtype: object

In [76]:
# mse = 1/n sum((y-ypred)^2)
# ypred = x*m + b
# dm = -2/n *sum(x(y-ypred))
# db = -2/n * sum(y-ypredd)
# mcurr = mcurr - learningRate * dm
#db = db -LearningRate *db
def gradientDescent(x,y):
    learningRate = .0001
    iteration =4
    m_curr = b_curr = 0
    n = len(x)
    for i in range(iteration):
        y_pred = x * m_curr + b_curr
        db= (-2/n)* sum(y-y_pred)
        dm = (-2/n) * sum(x * (y-y_pred))
        m_curr = m_curr - learningRate * dm
        b_curr = b_curr - learningRate *db
        
        cost = (1/n)*sum([val**2 for val in (y-y_pred)])
        print("cost {}, iteration {} m {}, b {} ".format(cost,i,m_curr,b_curr))
        
gradientDescent(df['math'],df['cs'])

cost 5199.1, iteration 0 m 0.9891800000000002, b 0.013980000000000001 
cost 46.3330473650399, iteration 1 m 1.0416176032, b 0.0147417592 
cost 31.852649863558305, iteration 2 m 1.0443971065873279, b 0.014802799669408 
cost 31.811952059367805, iteration 3 m 1.0445441606668626, b 0.014826693765467417 


In [51]:
#df.head(3)
# cost = 1/n * sum((y-ypred)^2)


In [ ]:
# we checked the corelation between math and cs score using gradient descent method which uses slope 

In [78]:
reg = LinearRegression()

reg.fit(df[['math']],df.cs)
df

name  math  cs
0   david    92  98
1   laura    56  68
2  sanjay    88  81
3     wei    70  80
4    jeff    80  83
5   aamir    49  52
6  venkat    65  66
7   virat    35  30
8  arthur    66  68
9    paul    67  73

In [80]:
reg.predict([[50]])

array([52.8020312])

In [97]:
# saving model to a file using joblib
import joblib


In [98]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [101]:
jm = joblib.load('model_joblib')
jm.predict([[50]])

array([52.8020312])

In [103]:
# using pickle
import pickle

jm.predict([[50]])

In [104]:
# writing a binary file (wb) in model_pickle file using pickle
with open ('model_pickle', 'wb') as f:
    pickle.dump(reg,f)

In [105]:
with open ('model_pickle','rb') as f:
    mpp = pickle.load(f)

In [107]:
mpp.predict([[50]])

array([52.8020312])